### ISSUE TITLE
cross-origin 

### ISSUE THREAD

**Issue by MildApocalypse** [MastaBaba/LoremFlickr#3]
Hey there

I'm new to programming but I'm fairly sure there's a problem with trying to manipulate image data on a canvas with an image on it that is hosted on loremflickr. This problem arises from a security issue with cross-orgin data in which the getImageData() call on a canvasrenderingcontext object will throw an error. This happens when using images from a non CORS-friendly host. I was hoping there was something you could do on your end to rectify it.

Cheers

**Comment by MastaBaba** [comment]
Wouldn't a practical solution be to copy the loremflickr image locally and then do the manipulation?

**Comment by MildApocalypse** [comment]
The program I am trying to create relies on applying an algorithm to a random image. The image has to be a 'green' image, meaning it has to come from somewhere that isn't considered a canned list of images. ie: I can't just copy your image manually every time i want to run the program, as it is supposed to be automatic. Your website was considered as such a candidate, but as i said it is impossible to to run the algorithm automatically as you cannot read the pixel data of a canvas object when the canvas contains cross-origin data.

**Comment by MastaBaba** [comment]
I understand that you wouldn't want to copy anything by hand. But couldn't you copy an image programatically to your local storage and then put it on the canvas from there?

**Comment by MastaBaba** [comment]
Hi again. CORS should now be enabled.

**Comment by MildApocalypse** [comment]
Thanks man, a whole class of people just got their programs working
