### ISSUE TITLE
Resolution dimensions

### ISSUE THREAD

**Issue by eladavron** [MastaBaba/LoremFlickr#4]
Will it be possible to only require one dimension for the resolution?
For example, if I go to `"http://loremflickr.com/320/dog"` it will get a dog picture with an X resolution of 320 and any Y resolution, or even just `"http://loremflickr.com/dog"` to get a dog picture with any resolution.
Or is that a flickr API restriction?

**Comment by MastaBaba** [comment]
It's possible with some trickery, but what would be the use case?

**Comment by eladavron** [comment]
I have a discord bot that displays a random dog image whenever someone types "~woof".
My current db (random.dog) is terribly small.
A solution like yours would be excellent for me, but I don't want to have to restrict it to a certain size.

**Comment by MastaBaba** [comment]
Couldn't you have the size parameters be generated randomly on your end,
and then request an image?

**Comment by eladavron** [comment]
Not a bad idea.
I won't make it completely random, but rather have it randomly choose between several predefined common sizes (I'm sure some are more common than others).
Thanks for the quick reply!

**Comment by MastaBaba** [comment]
No worries. 

Keep in mind that LoremFlickr crops images to match the dimensions you request. So, whatever dimensions you request, any photo could be returned, not just those that match a certain size.
