### ISSUE TITLE
Allow for some consistency

### ISSUE THREAD

**Issue by tremby** [MastaBaba/LoremFlickr#5]
It would be very useful in certain cases, especially in larger prototypes, to get some consistency in which random images are shown where on a page.

I'm aware that browser caching makes this possible to some degree by adding meaningless query strings to URLs, but I'd like for this to also work across different browsers and machines. (It's a little distracting if working with another developer and the page looks totally different on their screen.)

One way to achieve this would be to allow some user-provided string as part of the URL (whether query string or another slash-separated chunk). On the server side this would be hashed with whatever hashing algorithm is cheap, and then that hash wrapped into an integer. That integer can then be used to choose an image (such as `$possibleImages[$integer % count($possibleImages)]`), or the integer or hash or string can be used to seed the random number generator, or some other such scheme. The important thing is a repeatable result.

It wouldn't have to always produce the same image forever -- if the same string gave a different image a week or two down the line that's no big deal.

A possible extra benefit of something like this is that when such a request is served, it could have long caching headers attached to it, since you'd expect to serve the same image the next time the same request comes through. This would make LoremFlickr much more cachable (by a CDN proxy for example, or development teams' in-house caching HTTP proxies, etc) for such requests, hopefully reducing load on your end.

**Comment by MastaBaba** [comment]
I understand your point.

There are a bunch of little caveats with this, though. In part because of the multiple allowed parameters and in part because the Flickr API typically does not provide images in the same order when queried.

But, let me give this a bit of thought and see what I think makes sense.

**Comment by tremby** [comment]
I don't think it necessarily matters if Flickr gives images in a different order next time, if you're just reading from your local cache when possible anyway -- someone else making the same request soon afterwards will get the same image. Doesn't matter if it's then different the next day or the next week.

The multiple allowed parameters thing -- yes. This I think is a limitation of rest-style URL schemes. Optional and composable parameters just don't really fit into the mould. Query strings look uglier but make more sense in many cases!

**Comment by MastaBaba** [comment]
Have you seen the new 'lock' parameter?

**Comment by tremby** [comment]
It sounds good, but I think the documentation is a little fuzzy.

> Take some control of the image that's displayed. Include a `lock` query string parameter and give it a numeric value. While our cache is not updated, and sometimes for longer, the same image will be returned by our server.

On reading this, I have immediate questions:

- Can this number be arbitrarily large?
- Should it be at least 1, or is zero OK? Negative numbers?
- What effect if any do leading zeros have?
- A "numeric" value could be a float -- how are they handled? Is 1.0 the same as 1? Is 1.1 the same as 1? Is 1.1 the same as 1.10?

I'd answer these myself and suggest changes to the documentation, but I can't actually find where in the source code this "lock" parameter is handled. I don't see any reference to "lock" at all in this repo, nor in phpFlickr.

**Comment by tremby** [comment]
To answer some of them:

> Can this number be arbitrarily large?

It seems so, but huge numbers like 10000000000000000000000000000000000000000000, 10000000000000000000000000000000000000000001, 99999999999999999999999999999999999999999999 all seem to give the same result.

Additionally, 1000, 10000, 100000 all seem to give the same result (not the same as the huge numbers above) even though 100001 is different. Maybe it's capped to some maximum number, and then modulo 1000 or something?...

> Should it be at least 1, or is zero OK? Negative numbers?

- Zero is OK and distinct from 1.
- Negative numbers lead to a ton of errors (bug!): https://loremflickr.com/320/240?lock=-1

> What effect if any do leading zeros have?

None; 1 and 01 and 001 appear to be equivalent.

> A "numeric" value could be a float -- how are they handled? Is 1.0 the same as 1? Is 1.1 the same as 1? Is 1.1 the same as 1.10?

They appear to be truncated: 1, 1.0, 1.1, 1.9 all give the same result.

**Comment by MastaBaba** [comment]
Excellent questions :)

You will find that I've posted completely updated code at [this repository](https://github.com/MastaBaba/LoremFlickr-2).

There, you will see that the lock parameter is implicitly cast to an integer and then used to consistently return the same search result given the other provided parameters. This means that, using the lock parameter, the same image should be returned until the search cache is refreshed.
On LoremFlickr, this happens every 2 hours. I experimented with longer time frames, but that quickly crashed my server.

So, yeah, for best results, use an integer. The only relevant values are integers smaller than the number of results returned by Flickr given the other parameters provided, but is, on LoremFlickr, never more than 100.

And, that's probably why you see the same results for 1000, 10000 and 100000: all are 0 % 100. Same for 1, 01 and 001, all are 1 % 100.

**Comment by MastaBaba** [comment]
Also, thanks for spotting that bug!

**Comment by MastaBaba** [comment]
Bug fixed in the new repository.

**Comment by tremby** [comment]
For any others looking, the relevant code at the time of writing is here: https://github.com/MastaBaba/LoremFlickr-2/blob/master/image.php#L66

OK, all understood. I'd suggest just updating the docs a little to say "integer" rather than "numeric".

**Comment by MastaBaba** [comment]
Done.
