### ISSUE TITLE
Header Access-Control-Allow-Origin: * is missing when loading from cache

### ISSUE THREAD

**Issue by mgalante** [MastaBaba/LoremFlickr#7]
HI,
When a picture is loaded from cache header Access-Control-Allow-Origin: * is missing.

Access to Image at 'http://loremflickr.com/cache/images/9613e56670c083e23db82f469d199252.53.jpg' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8000' is therefore not allowed access.

Could you add those headers please?

**Comment by MastaBaba** [comment]
Can you check whether this is now working for you?

**Comment by mgalante** [comment]
Still having the same isssue:

http://loremflickr.com/cache/images/3bc59986afff98595bfa4f6384e4a71f.37.jpg

Response headers: 
HTTP/1.1 200 OK
Date: Sun, 03 Sep 2017 21:50:47 GMT
Content-Type: image/jpeg
Content-Length: 7018
Connection: keep-alive
Last-Modified: Sun, 03 Sep 2017 20:52:48 GMT
ETag: "59ac6ba0-1b6a"
X-Powered-By: PleskLin
CF-Cache-Status: HIT
Vary: Accept-Encoding
Expires: Mon, 04 Sep 2017 01:50:47 GMT
Cache-Control: public, max-age=14400
Accept-Ranges: bytes
Server: cloudflare-nginx
CF-RAY: 398bed3da26c52a8-MIA

Access-Control-Allow-Origin: * is missing :-(


But when loading from a not cached image its present:
**Access-Control-Allow-Origin:***
Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
CF-RAY:398bf1d953c25308-MIA
Connection:keep-alive
Content-Type:image/jpeg
Date:Sun, 03 Sep 2017 21:53:58 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Pragma:no-cache
Server:cloudflare-nginx
Transfer-Encoding:chunked
X-Powered-By:PleskLin
X-Powered-By:PHP/5.6.31


Maybe is because cloudflair cached from the old version?

**Comment by MastaBaba** [comment]
Odd. I can not replicate this. Though this is after I explicitly set Access-Control-Allow-Origin in .htaccess.

For me, now, also when receiving a cached image, Access-Control-Allow-Origin is properly set.

I tried this:

http://www.rexswain.com/cgi-bin/httpview.cgi?url=http://loremflickr.com/640/320&uag=Mozilla/5.0+(Macintosh%3B+Intel+Mac+OS+X+10_12_6)+AppleWebKit/603.3.8+(KHTML,+like+Gecko)+Version/10.1.2+Safari/603.3.8&ref=http://www.rexswain.com/httpview.html&aen=&req=GET&ver=1.1&fmt=AUTO

Which gave me this:

![rex_swain_s_http_viewer](https://user-images.githubusercontent.com/1337037/30007237-9dae1d96-90e0-11e7-82c3-8aa1713fb4e4.png)

There could be some CloudFlare-foo going on?
